# Generated by Django 5.0.2 on 2024-02-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_name",
                    models.CharField(default="Default Exercise Name", max_length=100),
                ),
                ("rep_count", models.IntegerField(default=0)),
                ("time_limit", models.IntegerField(default=0)),
            ],
        ),
    ]
