# Generated by Django 5.0.2 on 2024-02-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_profiledata_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiledata",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
